version: 0.1

phases:
  pre_build:
    commands:
      - sbt clean
  build:
    commands:
      - echo Build started on `date`
      - echo Run the test and package the code...
      - sbt test
      - sbt assembly
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir deploy
      - mkdir deploy/lib
      - cp target/scala-2.11/*.jar deploy/lib
      - aws cloudformation package --template-file infraTemplate.yaml --s3-bucket  codepipelineartifact-aws-common  --output-template-file infraOutputTemplate.yaml
artifacts:
  type: zip
  files:
    - deploy/lib/AWSfoodAgg-1.0.jar
    - infraOutputSamTemplate.yaml